### ISSUE TITLE
move tests to mesmer/tests?

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#122]
Our current folder structure is

```
mesmer
├── mesmer
└── tests
```

Can we move the tests folder below the mesmer folder? I.e. change this to:

```
mesmer
└── mesmer
    ├── tests
```

~Currently mesmer defines a package `tests` and I don't think this is what we want.~ Not entirely sure - it either defines a package tests or we cannot import it?

https://github.com/MESMER-group/mesmer/blob/df6dba2b6e7610604f1186280d99932480f4bcd6/setup.py#L76

We could exclude the tests folder but in some occasions it is helpful if the tests can be imported. If moved we can use `mesmer.tests`.

@znicholls?

**Comment by znicholls** [comment]
I think there are two schools of thought on this: 

1. tests should be part of the package (so they can be run after install to check things are working). In that case then `mesmer/mesmer/tests` makes sense
2. tests should not be part of the package. In that case then `mesmer/tests` makes sense

I would lean towards 2 here because our test data (particularly regression test) is not going to be small. The use of find packages in the way it is currently implemented is just wrong so I think we should fix that rather than changing the folder structure.
