### ISSUE TITLE
use 'modern' random number generator machinery

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#312]
We currently use `np.random.seed` and `np.random.multivariate_normal` which is discouraged by numpy. We should switch to the modern approach. See details in https://numpy.org/doc/stable/reference/random/index.html#module-numpy.random

To be considered together with #35, I realize this was already mentioned in #168

**Comment by mathause** [comment]
@veni-vidi-vici-dormivi I'd say this is also a milestone for v1 - the tricky part here is how to determine seeds for the different models (so that the emulations don't all have the same random noise, but are still deterministic).

**Comment by veni-vidi-vici-dormivi** [comment]
We could look into [`secret.randbits`](https://docs.python.org/3/library/secrets.html#secrets.randbits) for the generation of such seeds, then we should save it with the emulations. Or we could leave the choice of the seed to the user entirely and just give a hint that it should be different for each model since we don't provide infrastructure to fit for several models at once.

**Comment by mathause** [comment]
I like the idea of storing the seed with the emulations. Concerning the individual seeds, see

https://github.com/MESMER-group/mesmer/blob/f8287ba17e6b4221e51cfa5dff64f7c93d4f2358/mesmer/create_emulations/make_realisations.py#L15

I remember there was a discussion on numpy that it may be beneficial to have two seeds for each rng but I can't find that now (but maybe that was only for drawing random numbers in parallel).

Yes - `secrets.randbits` may be a good idea (numpy/numpy#25778)
