### ISSUE TITLE
why are emulations not stable?

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#402]
There is a test where we only check that 90% of the data is equal - this is ugly:

https://github.com/MESMER-group/mesmer/blob/00cabf9d5b56a5d970dff16f0bd4028f02f53ad6/tests/integration/test_draw_realisations_from_bundle.py#L105

Would be interesting to get to the bottom of this. However, could be nontrivial to figure out. My suspicion is that it comes from the matrix inversion.

- un-comment `assert_allclose` and check if this passes locally

   https://github.com/MESMER-group/mesmer/blob/00cabf9d5b56a5d970dff16f0bd4028f02f53ad6/tests/integration/test_draw_realisations_from_bundle.py#L113
- Do the same on GHA
- Potentially run on different OS on GHA (mac, win linux)
- Write a function to invert the matrices and check if this function leads to different results (see https://github.com/MESMER-group/mesmer/issues/168#issuecomment-1847271872)
- If we can identify `svd` as the culprit, this would be an additional motivation to save the 'inverted' covariance matrix (in addition to the speed gain, as it only needs to be inverted once).

**Comment by veni-vidi-vici-dormivi** [comment]
So I ran the test on atmos and locally and saved the result and the components of the emulations. The results were close, i.e. the tests passed. Weirdly, the final emulations were closer than `emus_lv` which differed for `atol = 1e-15`.  Not sure what to do from here...

**Comment by mathause** [comment]
Maybe this is no longer a problem... Can you open a PR to see if it also passes on github actions?

**Comment by veni-vidi-vici-dormivi** [comment]
See: https://github.com/numpy/numpy/blob/8b0bc6d062e09fb0392e1be8045dd0bf16b725d9/doc/neps/nep-0019-rng-policy.rst#L59

**Comment by veni-vidi-vici-dormivi** [comment]
Okay I'll do a wrap of this here but it is closely to semi-closely related to #408, #312, #168 and #35.
So in the global variability module we draw realizations from a multivariate normal. To achieve this one actually first draws from a standard univariate normal and then transforms these numbers to get values that have the desired mean and covariance like this (this is called colorizing): 
``` math
\mathbf{x} \sim \mathcal{N}(\mu, \Sigma) \Leftrightarrow
```
``` math
\mathbf{x}' \sim \mathcal{N}(\mathbf{0}, \mathbf{I}) \Leftrightarrow \mathbf{x}' = \left[\begin{matrix} x_0 \\ \vdots \\ x_n \end{matrix} \right] \sim \left[ \begin{matrix} \mathcal{N}(0,1) \\ \vdots \\ \mathcal{N}(0,1) \end{matrix}\right]
```
``` math
\mathbf{x} = \mu + A\cdot \mathbf{x}'  \text{\ \ \ with \ } A \cdot A^T = \Sigma
```

There are several methods to find a suitable matrix $A$ that transforms the standard normal values onto the desired distribution. Note that it says **a** suitable matrix since there are potentially infinite matrices fulfilling the condition $A \cdot A^T = \Sigma$. 
The function we use for drawing now is `numpy.random.multivariate_normal` which apparently uses singular value decomposition (`numpy.linalg.svd`) to do this. Singular value decomposition gives us three matrices $U$, $S$ and $V$, where $S$ has the singular values (=squared eigenvalues) of $\Sigma^T \Sigma$ in its diagonal and $U$ and $V$ are composed of eigenvectors of $\Sigma \Sigma^T$. To do this `numpy.linalg.svd` uses `np.linalg.eigh`.
Now this is where we run into problems because the eigenvectors of a matrix are not unique and in numpy apparently depend on the LAPACK configurations that is run on the machine, see link above. 

The third method however, Cholesky decomposition is indeed unique for positive definite matrices. Our matrices should be positive definite (not only semi-definite), since we do all the localizing and adjusting work. 

Thus it could be our best bet to use numpy's [modern random number generator with its multivariate normal method](https://github.com/numpy/numpy/blob/35b14fe3ffe18ca56c3896d441dd5edffcd177db/numpy/random/_generator.pyx#L3598) with Cholesky decomposition as mentioned in #312.

Then there is still the fact that for finding the localization radius for the covariance matrix we use actually `scipy.stats.multivariate_normal` and not numpy. I assume this is because scipy's version provides a method to get the logpdf which we need for cross validation that numpy does not. This is a little inconsistent and we could also consider to switching to scipy for both as scipy's version also has a method to draw from a distribution. 

But first more about the logpdf: to evaluate how well our localized covariances represent our data we compute the logpdf which represents the log likelihood of drawing the data we have from a distribution with this covariance. To do this one evaluates the pdf of a multivariate gaussian the definition of which contains the inverse of the covariance matrix as well as the determinant of the covariance matrix in a square root it the denominator of a fraction, leading to the fact that the covariance matrix has to be positive definite for this as well. However, one can refactor the definition to arrive at a point where it is also okay if it is just positive semidefinite, but we don't use that case, as it is not scipy's default. To get the determinant of the covariance matrix scipy uses `scipy.linalg.eigh` this function actually allows to choose the LAPACK driver in the background, but I have not done any research yet if that ensures that the eigenvectors are stable. Secondly, scipy whitens the samples (= transforms them to samples of a standard normal) so it can compute how 'far' the observations are from the expected outcome, keyword to look for here is Mahalanobis distance and I honestly did not understand it completely. But in any case for this we do a similar spiel as above. We get the transformation matrix needed by taking the eigenvectors it has already computed with `scipy.linalg.eigh`. However, by supplying the method with a covariance of a different class we could also make it use Cholesky or another method. 
Note: apparently no matrix inversion is happening anywhere here.

I think going for doing both with scipy would be the best option: We can use `scipy.stats.multivariate_normal.rvs` to draw random samples. We can supply this function with a random state to control how the samples are drawn and actually supply a numpy generator object which should yield the same result as with the numpy modern number generator. Per default scipy will colorize the matrix with the matrix it has gotten from the eigh call but we can again supply a covariance class that creates the matrix by means of Cholesky or something else. So a lot of options to choose from here. But by using scipy for both because it gives us the most freedom of how we want to do it. I'm not really a fan of the option of dragging around the transformation matrix tbh because this is exactly what these packages were made for and having in house multivariate normal distribution handling seems very inefficient...

**Comment by mathause** [comment]
> "see link above"

Do you mean the link in https://github.com/MESMER-group/mesmer/issues/402#issuecomment-1979171257?

> I'm not really a fan of the option of dragging around the transformation matrix tbh because this is exactly what these packages were made for and having in house multivariate normal distribution handling seems very inefficient...

We already carry around several covariance matrices, so adding $A$ would not be soo bad. However, I agree that we don't want to re-implement all of this.

---

Looking into scipy a bit more it is actually very flexible, as it allows us to pass `sp.stats.Covariance` and `np.random.Generator` instances.


```python
import numpy as np
import scipy as sp

# create random covariance matrix for testing
arr = np.random.randn(10, 10)
cov = arr @ arr.T

# draw multivariate samples using numpy
rng = np.random.default_rng(5)
samples_np = rng.multivariate_normal(np.zeros(10), cov, method="cholesky")

# draw multivariate samples using scipy, also with cholesky decomposition
L = np.linalg.cholesky(cov)
covariance = sp.stats.Covariance.from_cholesky(L)

rng = np.random.default_rng(5)
samples_sp = sp.stats.multivariate_normal.rvs(np.zeros(10), covariance, random_state=rng)

np.testing.assert_allclose(samples_np, samples_sp)
```

- See also the example of `sp.stats.Covariance.colorize`
- drawing random samples cholesky is much faster than svd

---

For `logpdf`

```python
data = np.atleast_2d(np.random.randn(100)).T

# calculate logpdf using cholesky
covariance = sp.stats.Covariance.from_cholesky(np.linalg.cholesky(cov))
sp.stats.multivariate_normal.logpdf(x=data, cov=covariance)

# calculate logpdf using svd
sp.stats.multivariate_normal.logpdf(x=data, cov=cov)
```

- See also `sp.stats.Covariance.whiten`
- I did some tests cholesky seems to be slower than svd for small cov (n=10) but faster for n=100 and much faster for n=1000. This could speed up `find_localized_empirical_covariance` considerably (maybe 5 times).

---

> Cholesky decomposition is indeed unique for positive definite matrices.

If cholesky is stable for the different machines that would solve the "instability" problem here (and make it considerably faster). So the last remaining question: is it a problem that we now require a positive definite covariance matrix?

**Comment by mathause** [comment]
> I think `sp.stats.multivariate_normal.logpdf(x=data, cov=cov)` with default parameters actually uses eigh() and not svd, but still good to know Cholesky is faster for our use case

Yes you are right.

For `rvs` (with default settings), however, the decomposition is done using `svd` (in `rng.multivariate_normal`). Strangely, `eigh` is called as well but not really used (in `_PSD`), which seems wasteful.

As discussed concerning cholesky requiring positive definite matrices: it is not necessarily guaranteed that the final `cov` is, because it is estimated from all samples and adjusted for the AR1 params, while this is not the case in the cross-validation loop. (argh)
