### ISSUE TITLE
MESMER-M: use coeffs from `order - 1` as first guess

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#422]
To fit the harmonic model, MESMER-M currently uses 0 as first guess. We could start from the coefficients from the previous order instead.

```python
first_guess = np.zeros(order * 4)
first_guess[:(order - 1) * 4] = coeffs
```

**Comment by veni-vidi-vici-dormivi** [comment]
Note to myself: This means when we fit for example for order two and order three by calling this function two separate times this would mean giving the call for order three the results from the fit to order two. This makes a lot of sense because by adding another order the results from the previous order only change by a small amount. This does NOT mean that the first guess for the third order **term** is the result from the fit of the second order **term**. The terms are independent from each other and can only be fit together.
