### ISSUE TITLE
Missing MESMER-X functions

### ISSUE THREAD

**Issue by veni-vidi-vici-dormivi** [MESMER-group/mesmer#438]
I went over the MESMER-X files and there are some things missing:
- some utils functions (`eval_param_distrib, read_form_fit_distrib, sigmoid_backtransf`)
  - https://github.com/MESMER-group/mesmer/blob/dce593bfa51bce7503175cf1026bea4d949773bc/mesmer/mesmer_x/create_emus_l_distrib.py#L13
- test_combination_vars 
  - https://github.com/MESMER-group/mesmer/blob/dce593bfa51bce7503175cf1026bea4d949773bc/mesmer/mesmer_x/temporary_support.py#L29C5-L29C25

I suspect we are missing a utils file? For some of these I can come up with a workaround (`test_combination_vars` and `eval_param_distrib`) but `read_form_distrib` and `sigmoid_back_trasf` it seems they are integral parts of MESMER-X. We will likely have to wait for @yquilcaille to clarify them.

**Comment by yquilcaille** [comment]
Actually, these 4 functions were used in the former version of MESMER-X. I forgot to remove them when finishing the refactoring. 
`eval_param_distrib, read_form_fit_distrib, sigmoid_backtransf` are entirely replaced now, so no need for them.
`test_combination_vars` was a function used to filter runs, so that when loading or using tas and any other climate variable, they would have the same esm, scenario and member. I didn't include this script, not to mess with the current solutions on data handling in MESMER.

**Comment by veni-vidi-vici-dormivi** [comment]
> are entirely replaced now, so no need for them

But they are still used in the code? What functions are they replaced by?

**Comment by yquilcaille** [comment]
Not used anymore.
`eval_param_distrib, read_form_fit_distrib` are replaced with a class `expression`.
`sigmoid_backtransf` is replaced with a function probability_integral_transform or something like that.
Actually, i think that `create_emus_l_distrib` is not useful anymore, it was also an old file.

Sorry that there is this mess of old and new files, but I had to rush the pull-request before vacations, so the former code isn't entirely cleaned. But the new code is here.

**Comment by veni-vidi-vici-dormivi** [comment]
Ahh I get it now, so the new files are the example, the train utils and train_l_distrib_mesmer_x, right?

**Comment by veni-vidi-vici-dormivi** [comment]
Got it thank you so much! With that we should be able to get everything cleaned up and running. Enjoy your vacation!
