### ISSUE TITLE
tag/ release not published on pypi

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#82]
Our tag did not trigger a release on pypi - probably because pushing a tag does not trigger the actions. Did we do it wrong? Or do we need to update the actions? xarray uses the following actions: https://github.com/pydata/xarray/blob/main/.github/workflows/pypi-release.yaml (i.e. a different trigger)

I can publish it manually but mesmer is not yet under my projects on pypi.

**Comment by leabeusch** [comment]
I'm gonna tag @znicholls here hoping/assuming he has very good answers to all of these questions.

**Comment by znicholls** [comment]
I think we need to update the actions. My great idea that we could do this on tags only in master seems to be impossible (https://github.community/t/run-workflow-on-push-tag-on-specific-branch/17519). 

> https://github.com/pydata/xarray/blob/main/.github/workflows/pypi-release.yaml (i.e. a different trigger)

Yep so that runs but doesn't run the tests first. I think the assumption with the xarray approach is that you only tag a build which is passing. That's not a bad assumption. The alternative is we assume people won't push v* tags to random branches. I don't mind either way.

> I can publish it manually but mesmer is not yet under my projects on pypi.

I just invited you again (maybe check your trash?).

**Comment by znicholls** [comment]
I just upload 0.8.1 manually to keep things moving: https://pypi.org/project/mesmer-emulator/0.8.1/

**Comment by mathause** [comment]
Thanks :rocket: Found the invitation again... :facepalm: No strong opinion here either.
